### ISSUE TITLE
What's the correct way to set the database connection not to auto-commit so we can handle transactions ourselves?

### ISSUE THREAD

**Issue by saoj** [klutzer/restapp#7]
That is not clear to me. Thanks!

**Comment by klutzer** [comment]
RestApp already handle transactions, since every request has its own connection and Hikari is configured to set new connections to auto-commit false. See: https://github.com/klutzer/restapp/blob/master/src/main/java/com/example/restapp/db/ConnectionManager.java#L22

And when the connection is cleared by `container.clear(Scope.THREAD)`: https://github.com/klutzer/restapp/blob/master/src/main/java/com/example/restapp/db/ConnectionManager.java#L96
